In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('C:\\Users\\sys8\\Downloads\\Iris.csv')

In [6]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
#checking missing values

df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [18]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iris-virginica
135    Iris-virginica
136    Iris-virginica
137    Iris-virginica
138    Iris-virginica
139    Iris-virginica
140    Iris-virginica
141    Iris-virginica
142    Iris-virginica
143    Iris-virginica
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [24]:
lb_make = LabelEncoder()
df["Species1"] = lb_make.fit_transform(df["Species"])
df[["Species", "Species1"]].head(100)

            Species  Species1
0       Iris-setosa         0
1       Iris-setosa         0
2       Iris-setosa         0
3       Iris-setosa         0
4       Iris-setosa         0
5       Iris-setosa         0
6       Iris-setosa         0
7       Iris-setosa         0
8       Iris-setosa         0
9       Iris-setosa         0
10      Iris-setosa         0
11      Iris-setosa         0
12      Iris-setosa         0
13      Iris-setosa         0
14      Iris-setosa         0
15      Iris-setosa         0
16      Iris-setosa         0
17      Iris-setosa         0
18      Iris-setosa         0
19      Iris-setosa         0
20      Iris-setosa         0
21      Iris-setosa         0
22      Iris-setosa         0
23      Iris-setosa         0
24      Iris-setosa         0
25      Iris-setosa         0
26      Iris-setosa         0
27      Iris-setosa         0
28      Iris-setosa         0
29      Iris-setosa         0
..              ...       ...
70  Iris-versicolor         1
71  Iris-versicolor         1
72  Iris-versicolor         1
73  Iris-versicolor         1
74  Iris-versicolor         1
75  Iris-versicolor         1
76  Iris-versicolor         1
77  Iris-versicolor         1
78  Iris-versicolor         1
79  Iris-versicolor         1
80  Iris-versicolor         1
81  Iris-versicolor         1
82  Iris-versicolor         1
83  Iris-versicolor         1
84  Iris-versicolor         1
85  Iris-versicolor         1
86  Iris-versicolor         1
87  Iris-versicolor         1
88  Iris-versicolor         1
89  Iris-versicolor         1
90  Iris-versicolor         1
91  Iris-versicolor         1
92  Iris-versicolor         1
93  Iris-versicolor         1
94  Iris-versicolor         1
95  Iris-versicolor         1
96  Iris-versicolor         1
97  Iris-versicolor         1
98  Iris-versicolor         1
99  Iris-versicolor         1

[100 rows x 2 columns]

In [40]:
y = df['Species1']

In [41]:
#splitting test train

x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.33,random_state=42)

In [49]:
x_train.shape

(100, 6)

In [50]:
x_test.shape

(50, 6)

In [51]:
y_test.shape

(50,)

In [52]:
y_train.shape

(100,)

In [55]:
model = KNeighborsClassifier(n_neighbors=6) # default value for n_neighbors is 5

In [56]:
# Train the model using the training sets and check score
model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [60]:
#Predict Output
predicted= model.predict(x_test)
predicted

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [61]:
#accuracy scores

model.score(x_test,y_test)

1.0

In [62]:
pd.concat([x_test, y_test, pd.Series(predicted, name='Predicted', index=x_test.index)], 
          ignore_index=False, axis=1)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species1,Species1,Predicted
73,74,6.1,2.8,4.7,1.2,1,1,1
18,19,5.7,3.8,1.7,0.3,0,0,0
118,119,7.7,2.6,6.9,2.3,2,2,2
78,79,6.0,2.9,4.5,1.5,1,1,1
76,77,6.8,2.8,4.8,1.4,1,1,1
31,32,5.4,3.4,1.5,0.4,0,0,0
64,65,5.6,2.9,3.6,1.3,1,1,1
141,142,6.9,3.1,5.1,2.3,2,2,2
68,69,6.2,2.2,4.5,1.5,1,1,1
82,83,5.8,2.7,3.9,1.2,1,1,1
110,111,6.5,3.2,5.1,2.0,2,2,2
12,13,4.8,3.0,1.4,0.1,0,0,0
36,37,5.5,3.5,1.3,0.2,0,0,0
9,10,4.9,3.1,1.5,0.1,0,0,0
19,20,5.1,3.8,1.5,0.3,0,0,0
56,57,6.3,3.3,4.7,1.6,1,1,1
104,105,6.5,3.0,5.8,2.2,2,2,2
69,70,5.6,2.5,3.9,1.1,1,1,1
55,56,5.7,2.8,4.5,1.3,1,1,1
132,133,6.4,2.8,5.6,2.2,2,2,2
29,30,4.7,3.2,1.6,0.2,0,0,0
127,128,6.1,3.0,4.9,1.8,2,2,2
26,27,5.0,3.4,1.6,0.4,0,0,0
128,129,6.4,2.8,5.6,2.1,2,2,2
131,132,7.9,3.8,6.4,2.0,2,2,2
145,146,6.7,3.0,5.2,2.3,2,2,2
108,109,6.7,2.5,5.8,1.8,2,2,2
143,144,6.8,3.2,5.9,2.3,2,2,2
45,46,4.8,3.0,1.4,0.3,0,0,0
30,31,4.8,3.1,1.6,0.2,0,0,0
22,23,4.6,3.6,1.0,0.2,0,0,0
15,16,5.7,4.4,1.5,0.4,0,0,0
65,66,6.7,3.1,4.4,1.4,1,1,1
11,12,4.8,3.4,1.6,0.2,0,0,0
42,43,4.4,3.2,1.3,0.2,0,0,0
146,147,6.3,2.5,5.0,1.9,2,2,2
51,52,6.4,3.2,4.5,1.5,1,1,1
27,28,5.2,3.5,1.5,0.2,0,0,0
4,5,5.0,3.6,1.4,0.2,0,0,0
32,33,5.2,4.1,1.5,0.1,0,0,0
142,143,5.8,2.7,5.1,1.9,2,2,2
85,86,6.0,3.4,4.5,1.6,1,1,1
86,87,6.7,3.1,4.7,1.5,1,1,1
16,17,5.4,3.9,1.3,0.4,0,0,0
10,11,5.4,3.7,1.5,0.2,0,0,0
81,82,5.5,2.4,3.7,1.0,1,1,1
133,134,6.3,2.8,5.1,1.5,2,2,2
137,138,6.4,3.1,5.5,1.8,2,2,2
75,76,6.6,3.0,4.4,1.4,1,1,1
109,110,7.2,3.6,6.1,2.5,2,2,2